# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - '/vendor/'

# Site settings
title: Yangeok
subtitle: 'Web Development Blog'
email: wooky92@naver.com
name: Yangwook Jeong
description: >
  Web Development Blog.
baseurl: ''
url: 'http://yangeok.github.io' # the base hostname & protocol for your site
cover: 'https://www.dropbox.com/s/nbvy0eonl84zzqo/header_image.jpg?dl=1'
logo: 'https://www.dropbox.com/s/d5o1gujoa24p9nf/logo.png?dl=1'

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/page:num/'
inter_post_navigation: false
highlightjs_theme: 'monokai-sublime'

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: yangeok

# Google analytics
ga_tracking_id: 'UA-125441608-1'

# Category descriptions (for archive pages)
# descriptions:
#   - cat: jekyll
#     desc: "Posts describing Jekyll setup techniques."

#   - cat: JAVASCRIPT
#     desc: "JAVASCRIPT"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@Theyangeok"               # (User) Name to display in the footer link
#     url:                                  # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Tistory blog
    icon: tumblr
    username: Yangeok
    url: https://yangwookee.tistory.com
    desc: Visit my daily life
    share: true

  # - name: Facebook
  #   icon: facebook
  #   username: theyangeok
  #   url:
  #   desc: Friend me on Facebook
  #   share: true

  - name: GitHub
    icon: github
    username: Yangeok
    url: https://github.com/yangeok
    desc: Fork me on GitHub
    share: false

  # - name: LinkedIn
  #   icon: linkedin
  #   username:
  #   url:
  #   desc: Connect with me on LinkedIn
  #   share: true

  # - name: Google+
  #   icon: google-plus
  #   username:
  #   url:
  #   desc: Add me to your Circles
  #   share: true

  # - name: YouTube
  #   icon: youtube
  #   username:
  #   url:
  #   desc: Subscribe on YouTube
  #   share: false

  - name: Instagram
    icon: instagram
    username: wooo_kee
    url: https://instagram.com/wooo_kee
    desc: Follow me on Instagram
    share: false

  # - name: Pinterest
  #   icon: pinterest
  #   username:
  #   url:
  #   desc: Follow me on Pinterest
  #   share: true
  # - name: SoundCloud
  #   icon: soundcloud
  #   username:
  #   url:
  #   desc: Follow me on SoundCloud
  #   share: false
  # - name: Tumblr
  #   icon: tumblr
  #   username:
  #   url:
  #   desc: Follow me on Tumblr
  #   share: false
  # - name: Steam
  #   icon: steam
  #   username:
  #   url:
  #   desc: Friend me on Steam
  #   share: false
  # - name: Dribbble
  #   icon: dribbble
  #   username:
  #   url:
  #   desc: Follow me on Dribble
  #   share: false
  # - name: Vimeo
  #   icon: vimeo-square
  #   username:
  #   url:
  #   desc: Follow me on Vimeo
  #   share: false
  # - name: Vine
  #   icon: vine
  #   username:
  #   url:
  #   desc: Follow me on Vine
  #   share: false
  # - name: Reddit
  #   icon: reddit
  #   username:
  #   url:
  #   desc: Share to Reddit
  #   share: true
  # - name: "Hacker News"
  #   icon: hacker-news
  #   username:
  #   url:
  #   desc: Share to Hacker News
  #   share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
  fb_image: '/assets/logo.png'
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: 'image/png'

  twitter_image: '/assets/logo.png'

  os_repo: 'https://github.com/yangeok/centrarium.com'
  os_rcs_type: 'git'
  os_src: 'git@github.com:yangeok/centrarium.com.git'
